### ISSUE TITLE
default cache dir for intake is `/tmp`, which won't work for Windows users.

### ISSUE THREAD

**Issue by NathanCummings** [ukaea/fair-mast#73]
Need to choose a more inclusive default.

Is this just a change to https://github.com/ukaea/fair-mast/blob/main/src/api/static/intake/level1.yml @samueljackson92 ?

**Comment by samueljackson92** [comment]
Yes. Should be all that is needed.

**Comment by samueljackson92** [comment]
This will fix the workaround in #74
