### ISSUE TITLE
Geometry data

### ISSUE THREAD

**Issue by NathanCummings** [ukaea/fair-mast#82]
We have now received many requests for geometry data to be included. We should start by adding what is listed below:

files with _M1 suffix: shots < 9990
files with _M4 suffix shots >= 9990
 
PF coils and vessel structure:
https://git.ccfe.ac.uk/MAST-U_Scheduler/efm/-/blob/master/EFIT/efit_data/pfcoils.dat_M1
[https://git.ccfe.ac.uk/MAST-U_Scheduler/efm/-/blob/master/EFIT/efit_data/pfcoils.dat_M](https://git.ccfe.ac.uk/MAST-U_Scheduler/efm/-/blob/master/EFIT/efit_data/pfcoils.dat_M1)4
 
Magnetic probes and flux loop locations:
https://git.ccfe.ac.uk/MAST-U_Scheduler/efm/-/blob/master/EFIT/efit_data/detectors.dat_M1
[https://git.ccfe.ac.uk/MAST-U_Scheduler/efm/-/blob/master/EFIT/efit_data/detectors.dat_M](https://git.ccfe.ac.uk/MAST-U_Scheduler/efm/-/blob/master/EFIT/efit_data/detectors.dat_M1)4

**Comment by samueljackson92** [comment]
I've put the documents shared by Nico in a shared folder within the HDPA/FAIR MAST sharepoint:
https://ukaeauk.sharepoint.com/:f:/s/CD-DataSolutions/Eox-A0IDTRVFkbGNG5n28hYBalVZJeClOUANRwIreNLQbA?e=mAtLNP
