### ISSUE TITLE
Python 3.12 does not work with setup

### ISSUE THREAD

**Issue by jameshod5** [ukaea/fair-mast#86]
When trying to run `uv sync` with python 3.12, there is an error trying to build pandas. We need to figure out why this happens (3.11 is fine), and what we can do to fix it. 

At the moment, the pyproject.toml is limiting python to 3.11 but we don't want to be restricted to certain python versions

**Comment by NathanCummings** [comment]
I just tested this and the tests passed for me. Updating pyproject.toml in #85 accordingly.
